"""Tests for src/kernel/generation_loop.py — the self-development cycle."""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import pytest

from src.kernel.capability_registry import Capability, CapabilityRegistry
from src.kernel.gap_detector import Gap
from src.kernel.generation_loop import (
    CycleResult,
    _log_operation,
    _parse_plan,
    run_cycle,
)
from src.kernel.model_interface import BudgetExceededError, ModelResponse
from src.kernel.self_modifier import ChangeResult


# --- Helpers ---

def _make_response(text: str, error: Optional[str] = None) -> ModelResponse:
    return ModelResponse(
        text=text, tokens_in=100, tokens_out=200,
        cost_estimate=0.001, model="test-model", provider="test",
        error=error,
    )


VALID_PLAN_JSON = json.dumps({
    "file_path": "src/tools/example.py",
    "description": "Example tool for testing.",
    "dependencies": [],
    "approach": "Write a simple function. Test it. Done.",
})

VALID_CODE = '''\
"""Example tool — generated by Archi."""

import logging

logger = logging.getLogger(__name__)


def example():
    """Do the example thing."""
    logger.info("Example executed.")
    return True
'''


# --- _parse_plan tests ---

class TestParsePlan:
    def test_valid_json(self):
        resp = _make_response(VALID_PLAN_JSON)
        plan = _parse_plan(resp)
        assert plan is not None
        assert plan["file_path"] == "src/tools/example.py"
        assert plan["description"] == "Example tool for testing."
        assert plan["dependencies"] == []

    def test_json_with_markdown_fences(self):
        resp = _make_response(f"```json\n{VALID_PLAN_JSON}\n```")
        plan = _parse_plan(resp)
        assert plan is not None
        assert plan["file_path"] == "src/tools/example.py"

    def test_invalid_json(self):
        resp = _make_response("not json at all")
        assert _parse_plan(resp) is None

    def test_missing_required_keys(self):
        resp = _make_response(json.dumps({"file_path": "x.py"}))
        assert _parse_plan(resp) is None

    def test_defaults_dependencies(self):
        plan_data = {
            "file_path": "src/x.py",
            "description": "Thing.",
            "approach": "Do it.",
        }
        resp = _make_response(json.dumps(plan_data))
        plan = _parse_plan(resp)
        assert plan is not None
        assert plan["dependencies"] == []


# --- _log_operation tests ---

class TestLogOperation:
    def test_writes_jsonl(self, tmp_path):
        log = tmp_path / "ops.jsonl"
        _log_operation("test_event", True, detail="hello", log_path=log)
        lines = log.read_text().strip().splitlines()
        assert len(lines) == 1
        entry = json.loads(lines[0])
        assert entry["event"] == "test_event"
        assert entry["success"] is True
        assert entry["detail"] == "hello"

    def test_appends(self, tmp_path):
        log = tmp_path / "ops.jsonl"
        _log_operation("a", True, log_path=log)
        _log_operation("b", False, log_path=log)
        lines = log.read_text().strip().splitlines()
        assert len(lines) == 2

    def test_missing_cap_field(self, tmp_path):
        log = tmp_path / "ops.jsonl"
        _log_operation("fail", False, missing_cap="web_search", log_path=log)
        entry = json.loads(log.read_text().strip())
        assert entry["missing_capability"] == "web_search"


# --- run_cycle tests ---

class TestRunCycleNoGaps:
    """When no gaps are detected, the cycle ends at observe."""

    def test_no_gaps_returns_observe(self, tmp_path):
        reg_path = tmp_path / "reg.json"
        registry = CapabilityRegistry(path=reg_path)
        # Register all kernel components so no structural gaps
        from src.kernel.gap_detector import KERNEL_COMPONENTS
        for name, module in KERNEL_COMPONENTS.items():
            registry.register(Capability(
                name=name, module=module, description=f"{name} cap",
            ))
        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
        )
        assert result.phase_reached == "observe"
        assert result.gap is None


class TestRunCyclePlanFailure:
    """Plan phase failures."""

    def test_plan_model_error(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")
        # Empty registry → structural gaps exist

        def failing_plan(prompt, system=None):
            return _make_response("", error="API down")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=failing_plan,
        )
        assert result.phase_reached == "plan"
        assert result.gap is not None
        assert "API down" in result.error

    def test_plan_parse_failure(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def bad_plan(prompt, system=None):
            return _make_response("I don't know what to do")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=bad_plan,
        )
        assert result.phase_reached == "plan"
        assert "parse" in result.error.lower()

    def test_plan_budget_exceeded(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def budget_plan(prompt, system=None):
            raise BudgetExceededError("Over budget")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=budget_plan,
        )
        assert result.phase_reached == "plan"
        assert "budget" in result.error.lower()


class TestRunCycleGenerateFailure:
    """Generate phase failures."""

    def test_generate_model_error(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def failing_gen(prompt, system=None):
            return _make_response("", error="Timeout")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=failing_gen,
        )
        assert result.phase_reached == "generate"
        assert result.plan is not None
        assert "Timeout" in result.error

    def test_generate_too_short(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def short_gen(prompt, system=None):
            return _make_response("x = 1")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=short_gen,
        )
        assert result.phase_reached == "generate"
        assert "short" in result.error.lower()

    def test_generate_budget_exceeded(self, tmp_path):
        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def budget_gen(prompt, system=None):
            raise BudgetExceededError("Over budget")

        result = run_cycle(
            repo_path="/fake", registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=budget_gen,
        )
        assert result.phase_reached == "generate"
        assert "budget" in result.error.lower()

    def test_generate_strips_markdown_fences(self, tmp_path):
        """Fences are stripped — code reaches integrate (fails on bad repo, but got past generate)."""
        import subprocess
        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        (repo / "README.md").write_text("init\n")
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def fenced_gen(prompt, system=None):
            return _make_response(f"```python\n{VALID_CODE}\n```")

        result = run_cycle(
            repo_path=str(repo), registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=fenced_gen,
        )
        # Should get past generate (code is long enough once fences stripped)
        assert result.phase_reached == "integrate"


class TestRunCycleIntegration:
    """Integration phase — uses a real git repo via self_modifier."""

    def test_full_cycle_success(self, tmp_path):
        """End-to-end: gap detected → plan → generate → test → register."""
        import subprocess
        # Set up a real git repo with passing tests
        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "kernel").mkdir(parents=True)
        (repo / "src" / "__init__.py").touch()
        (repo / "src" / "kernel" / "__init__.py").touch()
        (repo / "src" / "tools").mkdir(parents=True)
        (repo / "src" / "tools" / "__init__.py").touch()
        # Minimal conftest so pytest doesn't choke
        (repo / "tests").mkdir()
        (repo / "tests" / "__init__.py").touch()
        (repo / "tests" / "test_placeholder.py").write_text(
            "def test_true():\n    assert True\n"
        )
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "test@test.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "Test"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        reg_path = tmp_path / "reg.json"
        registry = CapabilityRegistry(path=reg_path)
        # Leave registry empty so structural gaps exist

        def good_plan(prompt, system=None):
            plan = {
                "file_path": "src/tools/example.py",
                "description": "Example tool.",
                "dependencies": [],
                "approach": "Write a simple function.",
            }
            return _make_response(json.dumps(plan))

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        result = run_cycle(
            repo_path=str(repo), registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=good_gen,
        )
        assert result.phase_reached == "integrate"
        assert result.capability_registered is True
        assert result.change is not None
        assert result.change.success is True
        # Verify capability was registered
        assert registry.has(result.gap.name)

    def test_full_cycle_test_failure(self, tmp_path):
        """Code that fails tests gets rolled back, capability not registered."""
        import subprocess
        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        (repo / "src" / "__init__.py").touch()
        (repo / "src" / "tools" / "__init__.py").touch()
        (repo / "tests").mkdir()
        (repo / "tests" / "__init__.py").touch()
        # A test that will fail when example.py is added (imports it)
        (repo / "tests" / "test_fail.py").write_text(
            "def test_fail():\n    assert False, 'intentional'\n"
        )
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")

        def good_plan(prompt, system=None):
            plan = {
                "file_path": "src/tools/example.py",
                "description": "Example tool.",
                "dependencies": [],
                "approach": "Write a function.",
            }
            return _make_response(json.dumps(plan))

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        result = run_cycle(
            repo_path=str(repo), registry=registry,
            log_path=tmp_path / "ops.jsonl",
            plan_fn=good_plan, generate_fn=good_gen,
        )
        assert result.phase_reached == "integrate"
        assert result.capability_registered is False
        assert result.change is not None
        assert result.change.success is False


class TestOperationLogFeedback:
    """Verify that operation log entries feed back into gap detection."""

    def test_failed_ops_create_operational_gaps(self, tmp_path):
        from src.kernel.gap_detector import detect_operational_gaps
        log = tmp_path / "ops.jsonl"
        _log_operation("cycle", False, missing_cap="web_search", log_path=log)
        _log_operation("cycle", False, missing_cap="web_search", log_path=log)
        gaps = detect_operational_gaps(log)
        assert len(gaps) == 1
        assert gaps[0].name == "web_search"
        assert gaps[0].source == "operational"
        assert len(gaps[0].evidence) == 2


class TestTestFailureDetailInLog:
    """When tests fail, the operation log should include the test output."""

    def test_test_output_included_in_detail(self, tmp_path):
        """When self_modifier returns failure_type=test_failure with test_output,
        the operation log detail should contain the actual test output so the
        planner can diagnose the failure on the next attempt."""
        from unittest.mock import patch as mock_patch
        import subprocess

        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        (repo / "README.md").write_text("init\n")
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")
        op_log = tmp_path / "ops.jsonl"

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        test_fail_result = ChangeResult(
            success=False, branch_name="archi/mod-test",
            file_path="src/tools/example.py",
            message="Rolled back src/tools/example.py — tests failed.",
            test_output="FAILED tests/test_foo.py::test_bar - AssertionError: expected 42 got 0",
            failure_type="test_failure",
        )
        with mock_patch("src.kernel.generation_loop.apply_change",
                        return_value=test_fail_result):
            result = run_cycle(
                repo_path=str(repo), registry=registry,
                log_path=op_log,
                plan_fn=good_plan, generate_fn=good_gen,
            )
        assert result.phase_reached == "integrate"
        assert result.change.failure_type == "test_failure"
        # Verify the operation log includes the test output
        log_lines = op_log.read_text().strip().splitlines()
        fail_entries = [
            json.loads(l) for l in log_lines
            if '"integrate_failed"' in l
        ]
        assert len(fail_entries) >= 1
        detail = fail_entries[-1]["detail"]
        assert "TEST OUTPUT" in detail
        assert "AssertionError" in detail

    def test_test_output_truncated_at_2000_chars(self, tmp_path):
        """Very long test output should be truncated to keep JSONL manageable."""
        from unittest.mock import patch as mock_patch
        import subprocess

        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        (repo / "README.md").write_text("init\n")
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")
        op_log = tmp_path / "ops.jsonl"

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        long_output = "X" * 5000
        test_fail_result = ChangeResult(
            success=False, branch_name="archi/mod-test",
            file_path="src/tools/example.py",
            message="Rolled back — tests failed.",
            test_output=long_output,
            failure_type="test_failure",
        )
        with mock_patch("src.kernel.generation_loop.apply_change",
                        return_value=test_fail_result):
            run_cycle(
                repo_path=str(repo), registry=registry,
                log_path=op_log,
                plan_fn=good_plan, generate_fn=good_gen,
            )
        log_lines = op_log.read_text().strip().splitlines()
        fail_entries = [
            json.loads(l) for l in log_lines
            if '"integrate_failed"' in l
        ]
        detail = fail_entries[-1]["detail"]
        # Should contain test output but be truncated
        assert "TEST OUTPUT" in detail
        assert len(detail) < 2200  # message + header + 2000 chars of output

    def test_no_test_output_when_empty(self, tmp_path):
        """When test_output is empty, detail should just be the message."""
        from unittest.mock import patch as mock_patch
        import subprocess

        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        (repo / "README.md").write_text("init\n")
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")
        op_log = tmp_path / "ops.jsonl"

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        test_fail_result = ChangeResult(
            success=False, branch_name="archi/mod-test",
            file_path="src/tools/example.py",
            message="Rolled back — tests failed.",
            test_output="",
            failure_type="test_failure",
        )
        with mock_patch("src.kernel.generation_loop.apply_change",
                        return_value=test_fail_result):
            run_cycle(
                repo_path=str(repo), registry=registry,
                log_path=op_log,
                plan_fn=good_plan, generate_fn=good_gen,
            )
        log_lines = op_log.read_text().strip().splitlines()
        fail_entries = [
            json.loads(l) for l in log_lines
            if '"integrate_failed"' in l
        ]
        detail = fail_entries[-1]["detail"]
        assert "TEST OUTPUT" not in detail
        assert detail == "Rolled back — tests failed."


class TestEnvironmentFailureRouting:
    """Environment failures log a different gap name than the original capability."""

    def test_environment_failure_logs_env_gap(self, tmp_path):
        """When self_modifier returns failure_type=environment, the op log
        should contain an env_* gap, not the original capability name."""
        from unittest.mock import patch as mock_patch
        import subprocess

        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "src" / "tools").mkdir(parents=True)
        subprocess.run(["git", "init"], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.email", "t@t.com"],
                       cwd=str(repo), capture_output=True)
        subprocess.run(["git", "config", "user.name", "T"],
                       cwd=str(repo), capture_output=True)
        (repo / "README.md").write_text("init\n")
        subprocess.run(["git", "add", "."], cwd=str(repo), capture_output=True)
        subprocess.run(["git", "commit", "-m", "init"],
                       cwd=str(repo), capture_output=True)

        registry = CapabilityRegistry(path=tmp_path / "reg.json")
        op_log = tmp_path / "ops.jsonl"

        def good_plan(prompt, system=None):
            return _make_response(VALID_PLAN_JSON)

        def good_gen(prompt, system=None):
            return _make_response(VALID_CODE)

        env_result = ChangeResult(
            success=False, branch_name="archi/mod-test",
            file_path="src/tools/example.py",
            message="Exception: dubious ownership in repository",
            error="dubious ownership in repository",
            failure_type="environment",
        )
        with mock_patch("src.kernel.generation_loop.apply_change",
                        return_value=env_result):
            result = run_cycle(
                repo_path=str(repo), registry=registry,
                log_path=op_log,
                plan_fn=good_plan, generate_fn=good_gen,
            )
        assert result.phase_reached == "integrate"
        assert result.change.failure_type == "environment"
        # Check the operation log has an env_ gap, not the original cap name
        log_lines = op_log.read_text().strip().splitlines()
        env_entries = [
            json.loads(l) for l in log_lines
            if "missing_capability" in l and "env_" in l
        ]
        assert len(env_entries) >= 1
        assert env_entries[-1]["missing_capability"].startswith("env_")
